#!/bin/bash

for CHL in `cat CHL_list.txt`
do
     	for SM in `cat SM_list.txt`
	do
		for CDOM in `cat CDOM_list.txt`
		do
			directory="/home/jxc4005/HYDROLIGHT/HL5.1/LUT1/CHL/"$CHL"/SM/"$SM"/CDOM/"$CDOM		
 			mkdir -p $directory
			echo $directory
			echo $directory >> directory_list.txt
			echo $CHL $SM $CDOM >> concentration_list.txt	
			mkdir -p $directory/ref	
			
			let i++			
			cat input.txt | sed 's"fla1"'$CHL'"g' | sed 's"fla2"'$CDOM'"g' | sed 's"fla3"'$SM'"g' > $directory/input.txt

  			cat HydRun.sh | sed 's"flag"'$directory'"g' > $directory/HydRun.sh
			cp ./CommonInputs/* $directory/
			sbatch --qos=cis-normal $directory/HydRun.sh

			echo $i
		done
	done
done 

